### ISSUE TITLE
Scala 3対応

### ISSUE THREAD

**Issue by xuwei-k** [t2v/holidays#38]
マクロをやめるか、マクロを真面目にScala 3のやつに移植する

(マクロをやめたほうがいい気はする)

**Comment by gakuzzzz** [comment]
joda-time のサポートを切るか、別jarにしてマクロ使わないようにした方が後々楽な気もしますねー。
joda-time の必要性もだんだん薄くなっていくでしょうし……

**Comment by gakuzzzz** [comment]
7.1 リリースしました
